modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/DAQEM/XLifeMod/issues"
license = "MIT"

[[mods]]
modId = "xlife"
version = "${version}"
displayName = "X Life"
authors = "DAQEM"
description = '''

'''
logoFile = "icon.png"

[[dependencies.xlife]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.xlife]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.xlife]]
modId = "architectury"
mandatory = true
versionRange = "[6.5.77,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.xlife]]
modId = "supermartijn642configlib"
mandatory = true
versionRange = "[1.1.8,)"
ordering = "AFTER"
side = "BOTH"